language: android
sudo: false
jdk:
    - oraclejdk8

android:
    components:
        - build-tools-26.0.2
        - tools
        - platform-tools
        - tools
          # The SDK version used to compile your project
        - android-26

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-26

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-26
        - sys-img-armeabi-v7a-android-
env:
    global:
        # Keep gradle from crapping all over the log
        - TERM=dumb
    matrix:
        - nodejs_version=8

install:
    # Install a sdkmanager version that supports the --licenses switch and
    # accept any Android SDK licenses. The output redirection prevents us from
    # hitting the travis log size limit of 4MB which would fail the build.
    - yes | sdkmanager tools > /dev/null
    - yes | sdkmanager --licenses > /dev/null

    - nvm install $nodejs_version
    - npm install
    - npm install -g cordova
    - npm install -g mobileui

script:
    - gradle --version
    - node --version
    - npm --version
    - cordova platform add android
    - cordova build android

deploy:
  provider: releases
  api_key: e3e2c5a3e853c59d50ed9388e25bf9cd92fe0f77
  file: "/home/travis/build/Alexandre-Muzulao/BoraBeber/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true

after_script:
    - codecov